<a href="https://colab.research.google.com/github/chad-casa/CASA0025/blob/main/CBFinal_W02_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 2 Lab

**Datasets**:

The following datasets are used in this lab.

- [nyc_subway_stations.tsv](https://storage.googleapis.com/qm2/CASA0025/nyc_subway_stations.tsv)
- [nyc_neighborhoods.tsv](https://storage.googleapis.com/qm2/CASA0025/nyc_neighborhoods.tsv)

In [ ]:
 %pip install duckdb duckdb-engine jupysql

Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.3.2)
Collecting duckdb-engine
  Downloading duckdb_engine-0.17.0-py3-none-any.whl.metadata (8.4 kB)
Collecting jupysql
  Downloading jupysql-0.11.1-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: packaging>=21 in /usr/local/lib/python3.12/dist-packages (from duckdb-engine) (25.0)
Requirement already satisfied: sqlalchemy>=1.3.22 in /usr/local/lib/python3.12/dist-packages (from duckdb-engine) (2.0.45)
Requirement already satisfied: prettytable>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from jupysql) (3.17.0)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.12/dist-packages (from jupysql) (0.5.5)
Requirement already satisfied: ipython-genutils>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from jupysql) (0.2.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from jupysql) (3.1.6)
Requirement already satisfied: sqlglot>=11.3.7 in /usr/local/lib/python3.12/dist-packages (from jupysql) (25.20.2)
Collecting jupysql-plugin>=0.4.2 (from jupysql)
  Downloading jupysql_plugin-0.4.5-py3-none-any.whl.metadata (7.8 kB)
Collecting ploomber-core>=0.2.7 (from jupysql)
  Downloading ploomber_core-0.2.27-py3-none-any.whl.metadata (532 bytes)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from ploomber-core>=0.2.7->jupysql) (6.0.3)
Collecting posthog>=3.0 (from ploomber-core>=0.2.7->jupysql)
  Downloading posthog-7.7.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.12.0->jupysql) (0.2.14)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.3.22->duckdb-engine) (3.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.3.22->duckdb-engine) (4.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->jupysql) (3.0.3)
Requirement already satisfied: requests<3.0,>=2.7 in /usr/local/lib/python3.12/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.32.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.17.0)
Requirement already satisfied: python-dateutil>=2.2 in /usr/local/lib/python3.12/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.9.0.post0)
Collecting backoff>=1.10.0 (from posthog>=3.0->ploomber-core>=0.2.7->jupysql)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: distro>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2026.1.4)
Downloading duckdb_engine-0.17.0-py3-none-any.whl (49 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 1.7 MB/s eta 0:00:00
Downloading jupysql-0.11.1-py3-none-any.whl (95 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.1/95.1 kB 4.5 MB/s eta 0:00:00
Downloading jupysql_plugin-0.4.5-py3-none-any.whl (192 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.8/192.8 kB 6.0 MB/s eta 0:00:00
Downloading ploomber_core-0.2.27-py3-none-any.whl (22 kB)
Downloading posthog-7.7.0-py3-none-any.whl (185 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.4/185.4 kB 7.1 MB/s eta 0:00:00
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Installing collected packages: backoff, posthog, duckdb-engine, ploomber-core, jupysql-plugin, jupysql
Successfully installed backoff-2.2.1 duckdb-engine-0.17.0 jupysql-0.11.1 jupysql-plugin-0.4.5 ploomber-core-0.2.27 posthog-7.7.0

In [ ]:
import duckdb

%load_ext sql

In [ ]:
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

## Question 1: Creating Tables

Create a database, then write a SQL query to create a table named `nyc_subway_stations` and load the data from the file `nyc_subway_stations.tsv` into it. Similarly, create a table named `nyc_neighborhoods` and load the data from the file `nyc_neighborhoods.tsv` into it.

In [ ]:
%sql duckdb:///:memory:
# %sql duckdb:///path/to/file.db

In [ ]:
%%sql

INSTALL httpfs;
LOAD httpfs;

Empty DataFrame
Columns: [Success]
Index: []

In [ ]:
# Add your code here.
%%sql

SELECT * FROM 'https://storage.googleapis.com/qm2/CASA0025/nyc_subway_stations.tsv';

,OBJECTID,ID,NAME,ALT_NAME,CROSS_ST,LONG_NAME,LABEL,BOROUGH,NGHBHD,ROUTES,TRANSFERS,COLOR,EXPRESS,CLOSED
0,1,376.0,Cortlandt St,None,Church St,"Cortlandt St (R,W) Manhattan","Cortlandt St (R,W)",Manhattan,None,"R,W","R,W",YELLOW,None,<NA>
1,2,2.0,Rector St,None,None,Rector St (1) Manhattan,Rector St (1),Manhattan,None,1,1,RED,None,<NA>
2,3,1.0,South Ferry,None,None,South Ferry (1) Manhattan,South Ferry (1),Manhattan,None,1,1,RED,None,<NA>
3,4,125.0,138th St,Grand Concourse,Grand Concourse,"138th St / Grand Concourse (4,5) Bronx","138th St / Grand Concourse (4,5)",Bronx,None,"4,5","4,5",GREEN,None,<NA>
4,5,126.0,149th St,Grand Concourse,Grand Concourse,149th St / Grand Concourse (4) Bronx,149th St / Grand Concourse (4),Bronx,None,4,"2,4,5",GREEN,express,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,487,909.0,JFK Terminal 8,None,None,"JFK Terminal 8, Queens",JFK Terminal 8,Queens,None,None,None,AIR-BLUE,None,<NA>
487,488,903.0,Federal Circle,Rental Car,None,"Federal Circle / Rental Car, Queens",Federal Circle / Rental Car,Queens,None,None,None,AIR-BLUE,None,<NA>
488,489,902.0,Long Term Parking,None,None,"Long Term Parking, Queens",Long Term Parking,Queens,None,None,None,AIR-BLUE,None,<NA>
489,490,901.0,Howard Beach,None,159th Ave,"Howard Beach, Queens",Howard Beach,Queens,None,None,A,AIR-BLUE,None,<NA>
490,491,900.0,Jamaica,Sutphin Blvd,Sutphin Blvd,"Jamaica / Sutphin Blvd, Queens",Jamaica / Sutphin Blvd,Queens,None,None,"E,J,Z",AIR-BLUE,None,<NA>

In [ ]:
%%sql

CREATE TABLE nyc_subway_stations AS SELECT * FROM 'https://storage.googleapis.com/qm2/CASA0025/nyc_subway_stations.tsv';

Empty DataFrame
Columns: [Success]
Index: []

In [ ]:
%%sql

FROM nyc_subway_stations;

,OBJECTID,ID,NAME,ALT_NAME,CROSS_ST,LONG_NAME,LABEL,BOROUGH,NGHBHD,ROUTES,TRANSFERS,COLOR,EXPRESS,CLOSED
0,1,376.0,Cortlandt St,None,Church St,"Cortlandt St (R,W) Manhattan","Cortlandt St (R,W)",Manhattan,None,"R,W","R,W",YELLOW,None,<NA>
1,2,2.0,Rector St,None,None,Rector St (1) Manhattan,Rector St (1),Manhattan,None,1,1,RED,None,<NA>
2,3,1.0,South Ferry,None,None,South Ferry (1) Manhattan,South Ferry (1),Manhattan,None,1,1,RED,None,<NA>
3,4,125.0,138th St,Grand Concourse,Grand Concourse,"138th St / Grand Concourse (4,5) Bronx","138th St / Grand Concourse (4,5)",Bronx,None,"4,5","4,5",GREEN,None,<NA>
4,5,126.0,149th St,Grand Concourse,Grand Concourse,149th St / Grand Concourse (4) Bronx,149th St / Grand Concourse (4),Bronx,None,4,"2,4,5",GREEN,express,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,487,909.0,JFK Terminal 8,None,None,"JFK Terminal 8, Queens",JFK Terminal 8,Queens,None,None,None,AIR-BLUE,None,<NA>
487,488,903.0,Federal Circle,Rental Car,None,"Federal Circle / Rental Car, Queens",Federal Circle / Rental Car,Queens,None,None,None,AIR-BLUE,None,<NA>
488,489,902.0,Long Term Parking,None,None,"Long Term Parking, Queens",Long Term Parking,Queens,None,None,None,AIR-BLUE,None,<NA>
489,490,901.0,Howard Beach,None,159th Ave,"Howard Beach, Queens",Howard Beach,Queens,None,None,A,AIR-BLUE,None,<NA>
490,491,900.0,Jamaica,Sutphin Blvd,Sutphin Blvd,"Jamaica / Sutphin Blvd, Queens",Jamaica / Sutphin Blvd,Queens,None,None,"E,J,Z",AIR-BLUE,None,<NA>

In [ ]:
%%sql

CREATE TABLE nyc_neighborhoods AS SELECT * FROM 'https://storage.googleapis.com/qm2/CASA0025/nyc_neighborhoods.tsv';

Empty DataFrame
Columns: [Success]
Index: []

In [ ]:
%%sql

FROM nyc_neighborhoods;

          BORONAME                      NAME
0         Brooklyn               Bensonhurst
1        Manhattan              East Village
2        Manhattan              West Village
3        The Bronx              Throggs Neck
4        The Bronx  Wakefield-Williamsbridge
..             ...                       ...
124       Brooklyn                  Red Hook
125         Queens   Douglastown-Little Neck
126         Queens                Whitestone
127         Queens                  Steinway
128  Staten Island                  Rosebank

[129 rows x 2 columns]

## Question 2: Column Filtering

Write a SQL query to display the `ID`, `NAME`, and `BOROUGH` of each subway station in the `nyc_subway_stations` dataset.

In [ ]:
# Add your code here.
%%sql

SELECT id, name, borough from nyc_subway_stations

        ID               NAME    BOROUGH
0    376.0       Cortlandt St  Manhattan
1      2.0          Rector St  Manhattan
2      1.0        South Ferry  Manhattan
3    125.0           138th St      Bronx
4    126.0           149th St      Bronx
..     ...                ...        ...
486  909.0     JFK Terminal 8     Queens
487  903.0     Federal Circle     Queens
488  902.0  Long Term Parking     Queens
489  901.0       Howard Beach     Queens
490  900.0            Jamaica     Queens

[491 rows x 3 columns]

## Question 3: Row Filtering

Write a SQL query to find all subway stations in the `nyc_subway_stations` dataset that are located in the borough of Manhattan.

In [ ]:
# Add your code here.
%%sql

SELECT id, name, borough from nyc_subway_stations

WHERE borough = 'Manhattan'

        ID                NAME    BOROUGH
0    376.0        Cortlandt St  Manhattan
1      2.0           Rector St  Manhattan
2      1.0         South Ferry  Manhattan
3    296.0            W 4th St  Manhattan
4    121.0            103rd St  Manhattan
..     ...                 ...        ...
135   72.0             Wall St  Manhattan
136  378.0        Whitehall St  Manhattan
137  491.0        Cortlandt St  Manhattan
138  492.0  World Trade Center  Manhattan
139   99.0            Times Sq  Manhattan

[140 rows x 3 columns]

## Question 4: Sorting Results

Write a SQL query to list the subway stations in the `nyc_subway_stations` dataset in alphabetical order by their names.

In [ ]:
# Add your code here.
%%sql

SELECT DISTINCT name FROM nyc_subway_stations ORDER BY name ASC;

                   NAME
0              103rd St
1              104th St
2              110th St
3              111th St
4              116th St
..                  ...
352            Woodlawn
353  World Trade Center
354         Wyckoff Ave
355             York St
356          Zerega Ave

[357 rows x 1 columns]

## Question 5: Unique Values

Write a SQL query to find the distinct boroughs represented in the `nyc_subway_stations` dataset.

In [ ]:
# Add your code here.
%%sql

SELECT DISTINCT borough FROM nyc_subway_stations ORDER BY borough;

         BOROUGH
0          Bronx
1       Brooklyn
2      Manhattan
3         Queens
4  Staten Island

## Question 6: Counting Rows

Write a SQL query to count the number of subway stations in each borough in the `nyc_subway_stations` dataset.

In [ ]:
%%sql

SELECT BOROUGH, COUNT(*) FROM nyc_subway_stations GROUP BY BOROUGH;

         BOROUGH  count_star()
0       Brooklyn           170
1         Queens            90
2      Manhattan           140
3          Bronx            69
4  Staten Island            22

In [ ]:
# Add your code here.
%%sql

SELECT COUNT(DISTINCT name) FROM nyc_subway_stations WHERE borough = 'Manhattan'

   count(DISTINCT "name")
0                      83

In [ ]:
%%sql

SELECT COUNT(DISTINCT name) FROM nyc_subway_stations WHERE borough = 'Queens'

   count(DISTINCT "name")
0                      82

In [ ]:
%%sql

SELECT COUNT(DISTINCT name) FROM nyc_subway_stations WHERE borough = 'Bronx'

   count(DISTINCT "name")
0                      59

In [ ]:
%%sql

SELECT COUNT(DISTINCT name) FROM nyc_subway_stations WHERE borough = 'Brooklyn'

   count(DISTINCT "name")
0                     130

In [ ]:
%%sql

SELECT COUNT(DISTINCT name) FROM nyc_subway_stations WHERE borough = 'Staten Island'

   count(DISTINCT "name")
0                      22

## Question 7: Aggregating Data

Write a SQL query to list the number of subway stations in each borough, sorted in descending order by the count.

In [ ]:
# Add your code here.
%%sql

SELECT borough, COUNT(DISTINCT name)
FROM nyc_subway_stations
GROUP BY borough
ORDER BY COUNT(name) DESC;

         BOROUGH  count(DISTINCT "name")
0       Brooklyn                     130
1      Manhattan                      83
2         Queens                      82
3          Bronx                      59
4  Staten Island                      22

## Question 8: Joining Tables

Write a SQL query to join the `nyc_subway_stations` and `nyc_neighborhoods` datasets on the borough name, displaying the subway station name and the neighborhood name.

In [ ]:
%%sql
select * from nyc_neighborhoods;

          BORONAME                      NAME
0         Brooklyn               Bensonhurst
1        Manhattan              East Village
2        Manhattan              West Village
3        The Bronx              Throggs Neck
4        The Bronx  Wakefield-Williamsbridge
..             ...                       ...
124       Brooklyn                  Red Hook
125         Queens   Douglastown-Little Neck
126         Queens                Whitestone
127         Queens                  Steinway
128  Staten Island                  Rosebank

[129 rows x 2 columns]

In [ ]:
%%sql

ALTER TABLE nyc_neighborhoods RENAME COLUMN column0 TO BORONAME;
ALTER TABLE nyc_neighborhoods RENAME COLUMN column1 TO NAME;
DELETE FROM nyc_neighborhoods WHERE BORONAME = 'BORONAME';

RuntimeError: (duckdb.duckdb.BinderException) Binder Error: Table "nyc_neighborhoods" does not have a column with name "column0"
[SQL: ALTER TABLE nyc_neighborhoods RENAME COLUMN column0 TO BORONAME;]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
%%sql

SELECT
    nyc_subway_stations.NAME AS STATION,
    nyc_neighborhoods.NAME AS NEIGHBORHOOD,
FROM
    nyc_subway_stations
JOIN
    nyc_neighborhoods
ON
    nyc_subway_stations.BOROUGH = nyc_neighborhoods.BORONAME;

                 STATION NEIGHBORHOOD
0           Cortlandt St    Chinatown
1              Rector St    Chinatown
2            South Ferry    Chinatown
3               W 4th St    Chinatown
4                15th St     Red Hook
...                  ...          ...
11053     JFK Terminal 8   Auburndale
11054     Federal Circle   Auburndale
11055  Long Term Parking   Auburndale
11056       Howard Beach   Auburndale
11057            Jamaica   Auburndale

[11058 rows x 2 columns]

In [ ]:
# Add your code here.
%%sql
ROLLBACK;
SELECT nyc_subway_stations.name, nyc_neighborhoods.name, nyc_neighborhoods.BORONAME, nyc_subway_stations.borough FROM nyc_subway_stations INNER JOIN nyc_neighborhoods ON nyc_subway_stations.borough = nyc_neighborhoods.BORONAME;

                    NAME      NAME_1   BORONAME    BOROUGH
0           Cortlandt St   Chinatown  Manhattan  Manhattan
1              Rector St   Chinatown  Manhattan  Manhattan
2            South Ferry   Chinatown  Manhattan  Manhattan
3               W 4th St   Chinatown  Manhattan  Manhattan
4                15th St    Red Hook   Brooklyn   Brooklyn
...                  ...         ...        ...        ...
11053     JFK Terminal 8  Auburndale     Queens     Queens
11054     Federal Circle  Auburndale     Queens     Queens
11055  Long Term Parking  Auburndale     Queens     Queens
11056       Howard Beach  Auburndale     Queens     Queens
11057            Jamaica  Auburndale     Queens     Queens

[11058 rows x 4 columns]

## Question 9: String Manipulation

Write a SQL query to display the names of subway stations in the `nyc_subway_stations` dataset that contain the word "St" in their names.

In [ ]:
# Add your code here.
%%sql
SELECT name FROM nyc_subway_stations WHERE name LIKE '%St%';

              NAME
0     Cortlandt St
1        Rector St
2         138th St
3         149th St
4         149th St
..             ...
225  Beach 98th St
226        Main St
227    Steinway St
228      St George
229      Stapleton

[230 rows x 1 columns]

## Question 10: Filtering with Multiple Conditions

Write a SQL query to find all subway stations in the `nyc_subway_stations` dataset that are in the borough of Brooklyn and have routes that include the letter "R".

In [ ]:
# Add your code here.
%%sql
SELECT Name FROM nyc_subway_stations WHERE borough ='Brooklyn' AND ROUTES like '%R%';

             NAME
0         25th St
1         36th St
2         45th St
3         53rd St
4         59th St
5         77th St
6         86th St
7         95th St
8          9th St
9   Bay Ridge Ave
10       Court St
11     DeKalb Ave
12    Lawrence St
13     Pacific St
14   Prospect Ave
15       Union St

Once you've completed your attempt, you can check your answers [here](https://github.com/oballinger/CASA0025/blob/main/notebooks/W02_lab_solution.ipynb).